### ISSUE TITLE
Permissions help

### ISSUE THREAD

**Issue by JuniorTheNoob** [DevLeoko/AdvancedBan#116]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 Latest
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
1.8

_Please provide the EXACT steps required to reproduce the problem..._
1.Install plugin
2.Change plugin name (advancebans ---> GalacticBans)
3.Add permissions manually in bungee config.yml

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._

_Add any additional information below._
It say's I dont have permissions. Even though I'm opped and adding all permissions to admin in bungee config.yml

**Comment by Beelzebu** [comment]
Spigot and BungeeCord work the permissions separately, bungee brings an integrated system of permissions which can be configured in the config.yml.
This means that in order to make use of the permissions that are added to a group you must add the user to the groups (that I think is the problem here, you should paste your bungeecord config.yml and your bungee plugin list). Personally, I see this as something very complicated and slow to manage permissions because there are currently several plugins that allow you to synchronize bungeecord and spigot permissions using databases like LuckPerms or PowerfulPerms.

**Comment by DevLeoko** [comment]
Closed due to no response but I assume it's solved ;)
