### ISSUE TITLE
DateBase problem

### ISSUE THREAD

**Issue by ExsodusGames** [DevLeoko/AdvancedBan#218]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 AdvancedBan-2.1.6-SNAPSHOT
 
_What kind of server do you have (`Bungeecord/single server`)?_
 BungeeCord
 
_What server version (/version) are you using?_
BungeeCord-BotFilter 3.1.1 
Latest kernel version - http://www.rubukkit.org/threads/137038/

_Please provide the EXACT steps required to reproduce the problem..._
1. To connect to the database
2. Join to the server
(**Explanation: The database was empty in advance!**)

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/34gtJpk0

_Add any additional information below._
https://pastebin.com/zaLZ25HU

**Comment by ExsodusGames** [comment]
The release that is hosted on Spigot it throws another error:
https://pastebin.com/4CJ5tGLw

**Comment by DevLeoko** [comment]
Paste the output of /advancedban

**Comment by SlickNicky10** [comment]
Using MySQL on AdvancedBan 2.1.4-RELEASE on Spigot 1.12.2 and often this error will be logged:

An unexpected error has ocurred executing an Statement in the database
Please check the debug.log file in the plugin's folder and report thiserror in: https://github.com/DevLeoko/AdvancedBan/issues
Debug: Query: 
SELECT * FROM `Punishments` WHERE `uuid` = ? OR `uuid` = ?
Debug: An error has ocurred with the database, the error code is: '0'
The state of the sql is: 08S01
Error message: Communications link failure

The last packet successfully received from the server was 3,976,986 milliseconds ago.  The last packet sent successfully to the server was 948,872 milliseconds ago.
An unexpected error has ocurred executing an Statement in the database
Please check the debug.log file in the plugin's folder and report thiserror in: https://github.com/DevLeoko/AdvancedBan/issues
Debug: Query: 
SELECT * FROM `Punishments` WHERE `uuid` = ? OR `uuid` = ?
Debug: An error has ocurred with the database, the error code is: '0'
The state of the sql is: 08S01
Error message: Communications link failure

The last packet successfully received from the server was 8,873,428 milliseconds ago.  The last packet sent successfully to the server was 8,873,429 milliseconds ago.

Additional problems caused by this?:

It will cause players to be stuck on the "Logging in..." screen while connecting to the server until they get the "Connection Lost: Disconnected" message from Minecraft. Here is an additional line from the console that could potentially help you figure out the problem:

[Thu, 14. Jun 2018 03:01:50 CEST ERROR] Could not pass event AsyncPlayerPreLoginEvent to AdvancedBan v2.1.4-RELEASE

Interestingly, when I installed the plugin "PlugMan" on my server and created a Skript to make PlugMan restart AdvancedBan every 5 minutes the logging in issue was gone. Great! Now there's a new problem doing this does:

Restarting the plugin means there is a few seconds where AdvancedBan is unloaded. This can lead to the following issue:

* Players that are supposed to be banned can connect to the server. AdvancedBan somehow does not see the player when its done loading and does not kick them.

Please fix this or I will be forced to move to another plugin, it's a shame because AdvancedBan is a really cool plugin, and for free too ❤

**Comment by DevLeoko** [comment]
@SlickNicky10 you are running on an old version. 2.1.5 is the latest stable one

**Comment by SlickNicky10** [comment]
@DevLeoko Then you have a different problem. Because the console tries to tell me 2.1.3 is the latest version

**Comment by Beelzebu** [comment]
Seems that you're using a old version that still uses the old update checker @SlickNicky10
