### ISSUE TITLE
Warn / ban-ip issues

### ISSUE THREAD

**Issue by crsglobalmusic** [DevLeoko/AdvancedBan#338]
Please remove this thread.

**Comment by crsglobalmusic** [comment]
![ban and unban ip with check](https://user-images.githubusercontent.com/64709265/80894147-474d4d00-8ce1-11ea-9fb2-451ba5132d17.png)
![console banip showing](https://user-images.githubusercontent.com/64709265/80894150-5207e200-8ce1-11ea-9c1a-a71237736ba9.png)
![unban normal try](https://user-images.githubusercontent.com/64709265/80894151-5af8b380-8ce1-11ea-9bc1-611df385be0b.png)
![join succes](https://user-images.githubusercontent.com/64709265/80894158-64821b80-8ce1-11ea-8311-e2297f79ebf8.png)
![warn player + warns list](https://user-images.githubusercontent.com/64709265/80894160-6a77fc80-8ce1-11ea-9008-2c3a6a07eafa.png)
![warn delete](https://user-images.githubusercontent.com/64709265/80894166-7794eb80-8ce1-11ea-969d-6105f9f2aaa9.png)
![still have warn](https://user-images.githubusercontent.com/64709265/80894172-7b287280-8ce1-11ea-8d99-a63c61dfdc8e.png)
![unwarn clear](https://user-images.githubusercontent.com/64709265/80894173-7d8acc80-8ce1-11ea-9f97-b39a7cddf75f.png)

**Comment by DevLeoko** [comment]
Thanks for the extensive issue report and sorry for the trouble.

```
What is the use of /unbanip if it can't unbanip a player?
```
The use of "unbanip" depends on the plugin you have that has this command. AdvancedBan does not have the command "unbanip" this is also why your unban only worked when you did it for the second time as you then used "unban" instead of "unbanip".

```
What is the use of /unwarn if it can't unwarn a player?
```
This question comes off a bit rude as the use of /unwarn is obviously to unwarn a player. Please don't do that when asking for help/reporting a bug.
Anyway, this seems to be a bug with caching. I've already figured out what is going wrong and it should be fixed in the next release.

**Comment by crsglobalmusic** [comment]
Thank you sir for the support.

**Comment by crsglobalmusic** [comment]
Do you mind if i ask when will be a next release? 

Thank you in advance.

**Comment by DevLeoko** [comment]
I'm currently not working on advanced ban, so I can't say, sorry.

**Comment by DevLeoko** [comment]
Please don't close this issue, as the bug has not been solved yet

**Comment by DevLeoko** [comment]
This bug should be fixed in the latest version of AdvancedBan.
https://www.spigotmc.org/resources/advancedban.8695/update?update=335170
Sorry for the trouble and feel free to reopen this issue if the bug persists.
