### ISSUE TITLE
Server freeze

### ISSUE THREAD

**Issue by Dilbry** [DevLeoko/AdvancedBan#443]
AdvancedBan 2.3.0
 
Single server

Paper 1.16.4

sudden freeze

https://pastebin.com/HJKyA1wT

**Comment by Dilbry** [comment]
And what is it?

https://pastebin.com/RQeLY12i

**Comment by DevLeoko** [comment]
There are all kinds of other plugins in that log as well. Are you doing something specific that leads you to believe that this is actually caused by AdvancedBan?

**Comment by Dilbry** [comment]
I issued a ban to one person, after which the server froze, after which it returned to its normal state and similar problems appeared. Everything would be fine, freeze for 7-15 seconds, but players kicks from the server.

**Comment by A248** [comment]
The stacktrace of your server thread at the time of the thread dump indicates your server is simply overloaded performing normal vanilla game operations.

This line is merely a helpful notice from a library AdvancedBan uses, which also detected the slowdown:
```
[14:29:15] [HikariPool-1 housekeeper/WARN]: [me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool] HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m54s575ms550µs284ns).
```

Other than that, there is nothing in the thread dump indicating this is caused by AdvancedBan. There are threads opening and closing connections, but those are completely normal and will certainly not crash your server.

**Comment by A248** [comment]
You're welcome to join the discord off-topic channel where you might get more assistance or further resources to deal with your server crash.

**Comment by Dilbry** [comment]
Ok, thank you for help.
