### ISSUE TITLE
How can I change the "Console"

### ISSUE THREAD

**Issue by ghost** [DevLeoko/AdvancedBan#526]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.3.0
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Single
 
_What server version (/version) are you using?_
1.8.8

_Please provide the EXACT steps required to reproduce the problem..._
"You have been banned by %OPERATOR%"  (Instead of OPERATOR, the person who gives the punishment writes). 
It says "You have been banned by Console" when someone automatically bans.

How can I change the "Console"?

**Comment by Hopefuls** [comment]
This is not possible with the current AdvancedBan version without modifying the source code, though if you wish to go that length, take a look at this line
https://github.com/DevLeoko/AdvancedBan/blob/5c7257736a8f64363dfb33aa171d023117ec4fdc/core/src/main/java/me/leoko/advancedban/utils/commands/PunishmentProcessor.java#L72

This is the Name from the corresponding CommandSender, if this is a player, the players name will be used, if the CommandSender is the console, the String `CONSOLE` will be used.

In order to change this to whatever you want, you will have to check first if the CommandSender is a player or the console, then have the string change accordingly.
